name: Add firmware binary on release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Build firmware
        uses: ./.github/workflows/build-firmware.yml@main
      - name: Upload firmware binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "Firmware/src/main.bin"
